name: Docker Registry

on:
    schedule:
        # https://crontab.guru/#0_8_*_*_*
        - cron: '0 4 * * *' # everyday at 04AM 
    workflow_dispatch:
    push:
        branches:
            - '**'
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - 'master'

jobs:
    docker:
        name: Build image and push to GCR
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Docker metainformation
                id: docker_meta
                uses: crazy-max/ghaction-docker-meta@v3.1.0
                with:
                    images: |
                        ghcr.io/it2901-sintef01/backend
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Cache Docker layers
                uses: actions/cache@v2.1.5
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -   name: Login to GitHub Container Registry
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.CR_PAT }}
            -   name: Build and push production image
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.docker_meta.outputs.tags }},ghcr.io/it2901-sintef01/backend:${{ github.sha }} # Add the SHA as a tag 
                    labels: ${{ steps.docker_meta.outputs.labels }}
    azure:
      name: Deploy Docker image to Azure
      runs-on: ubuntu-20.04
      if: github.ref == 'refs/heads/master' # only deploy to azure on master
      needs: docker
      steps:
            - uses: azure/docker-login@v1
              with:
                login-server: contoso.azurecr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.CR_PAT }}
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'sintef01'
                slot-name: 'production'
                publish-profile: ${{ secrets.AzureAppService_PublishProfile_dd3ecfac72f8439fba924ded08761b45 }}
                images: 'ghcr.io/it2901-sintef01/backend:${{ github.sha }}'
