name: Docker Registry

on:
    workflow_dispatch:
    push:
        branches: [ master ]
        paths-ignore:
            - "**.md"
        tags:
            - "*"

jobs:
    login:
        name: Push built image to GHCR
        runs-on: ubuntu-latest
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Cache Docker layers
                uses: actions/cache@v2.1.4
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.CR_PAT }}
            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ghcr.io/it2901-sintef01/backend:latest
